
add_newline = false

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$env_var\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$character """

[character]
success_symbol = '>>>'
error_symbol = '>>>'

[time]
disabled = false
